import {
  Activity,
  ArrowUpRight,
  Compass,
  Download,
  FileText,
  Mail,
  MapPin,
  Plug,
  Sparkles,
} from 'lucide-react';
import { BW_MARK_PATH, BW_MARK_VIEWBOX } from '@/lib/brand-mark';

export type IconProps = React.SVGProps<SVGSVGElement> & {
  /** Accepted so brand marks and lucide icons share one call signature. */
  strokeWidth?: number | string;
};

/* lucide-react 1.x dropped brand icons, so the two we need are inlined here as
   filled marks. They ignore `strokeWidth`, which is expected for brand logos. */

function LinkedinMark(props: IconProps) {
  return (
    <svg viewBox="0 0 24 24" fill="currentColor" {...props}>
      <path d="M20.45 20.45h-3.56v-5.57c0-1.33-.03-3.04-1.85-3.04-1.86 0-2.14 1.45-2.14 2.94v5.67H9.35V9h3.41v1.56h.05c.48-.9 1.64-1.85 3.37-1.85 3.6 0 4.27 2.37 4.27 5.46v6.28ZM5.34 7.43a2.07 2.07 0 1 1 0-4.13 2.07 2.07 0 0 1 0 4.13Zm1.78 13.02H3.55V9h3.57v11.45ZM22.22 0H1.77C.79 0 0 .77 0 1.72v20.56C0 23.23.79 24 1.77 24h20.45c.98 0 1.78-.77 1.78-1.72V1.72C24 .77 23.2 0 22.22 0Z" />
    </svg>
  );
}

function GithubMark(props: IconProps) {
  return (
    <svg viewBox="0 0 24 24" fill="currentColor" {...props}>
      <path d="M12 .5C5.73.5.5 5.73.5 12a11.5 11.5 0 0 0 7.86 10.92c.58.1.79-.25.79-.56v-2.17c-3.2.7-3.88-1.37-3.88-1.37-.53-1.34-1.29-1.7-1.29-1.7-1.06-.72.08-.71.08-.71 1.17.08 1.79 1.2 1.79 1.2 1.04 1.78 2.72 1.27 3.39.97.1-.75.41-1.27.74-1.56-2.56-.29-5.25-1.28-5.25-5.7 0-1.26.45-2.29 1.19-3.1-.12-.29-.52-1.46.11-3.05 0 0 .97-.31 3.18 1.18a11 11 0 0 1 5.79 0c2.2-1.49 3.17-1.18 3.17-1.18.63 1.59.23 2.76.12 3.05.74.81 1.18 1.84 1.18 3.1 0 4.43-2.69 5.4-5.26 5.69.42.36.8 1.08.8 2.18v3.23c0 .31.2.67.8.56A11.5 11.5 0 0 0 23.5 12C23.5 5.73 18.27.5 12 .5Z" />
    </svg>
  );
}

/**
 * The bw monogram.
 *
 * Inlined rather than loaded as a file so it inherits `currentColor` and
 * inverts with the nav as it crosses light and dark panels, which an <img>
 * cannot do. The path comes from `lib/brand-mark.ts`, which is generated by
 * `scripts/build_brand.py` alongside everything in `brand/`, so the geometry
 * lives in exactly one place.
 */
export function BwMark(props: IconProps) {
  return (
    <svg viewBox={BW_MARK_VIEWBOX} aria-hidden="true" {...props}>
      <path fill="currentColor" fillRule="evenodd" d={BW_MARK_PATH} />
    </svg>
  );
}

/**
 * The only place icons are wired up. `data/content.ts` refers to these by key,
 * so copy edits never touch a component. Add new entries here first.
 */
export const icons = {
  activity: Activity,
  arrowUpRight: ArrowUpRight,
  compass: Compass,
  download: Download,
  fileText: FileText,
  github: GithubMark,
  linkedin: LinkedinMark,
  mail: Mail,
  mapPin: MapPin,
  plug: Plug,
  sparkles: Sparkles,
} satisfies Record<string, React.ComponentType<IconProps>>;

export type IconKey = keyof typeof icons;
